-- any sql that is to be pre-loaded before testsuite runs goes in here
-- statements must be a single line without returns

INSERT INTO PHONE(ID,AREACODE,PHONENUMBER,TYPE) VALUES(2,'91','12345678','LANDLINE')
INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME, SALARY, ADDR_ID, VERSION) VALUES (3, 'John', 'Matthews',1500.00, NULL , 1)
INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME, SALARY, ADDR_ID, VERSION) VALUES (10, 'John', 'Matthews',1500.00, NULL , 1)
INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME, SALARY, ADDR_ID, VERSION) VALUES (11, 'John', 'Matthews',1500.00, NULL , 1)
INSERT INTO PHONE (ID,AREACODE,PHONENUMBER,TYPE, EMPLOYEE_ID) VALUES(10,'91','12345678','LANDLINE',10)
INSERT INTO PHONE (ID,AREACODE,PHONENUMBER,TYPE, EMPLOYEE_ID) VALUES(11,'97','65465165','MOBILE',11)
INSERT INTO PHONE (ID,AREACODE,PHONENUMBER,TYPE, EMPLOYEE_ID) VALUES(12,'98','99872366','FAX',10)
INSERT INTO PHONE (ID,AREACODE,PHONENUMBER,TYPE, EMPLOYEE_ID) VALUES(13,'91','12345678','LANDLINE',11)
INSERT INTO PHONE (ID,AREACODE,PHONENUMBER,TYPE, EMPLOYEE_ID) VALUES(14,'51','12334568','FAX',10)