-- any sql that is to be pre-loaded before testsuite runs goes in here
-- statements must be a single line without returns
INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME,SALARY,ADDR_ID, VERSION) VALUES (2, 'Sharon', 'Matthews',3500.00, NULL , 1)
INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME,SALARY,ADDR_ID, VERSION) VALUES (3, 'John', 'Matthews',1500.00, NULL , 1)
INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME,SALARY,ADDR_ID, VERSION) VALUES (4, 'Michael', 'Matthews',2500.00, NULL , 1)
INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME,SALARY,ADDR_ID, VERSION) VALUES (5, 'Steve', 'Matthews',9500.00, NULL , 1)
INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME,SALARY,ADDR_ID, VERSION) VALUES (6, 'Tor', 'Matthews',7500.00, NULL , 1)
INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME,SALARY,ADDR_ID, VERSION) VALUES (7, 'Dan', 'Matthews',500.00, NULL , 1)
